--View to source RFL and NMUH CWT Radiotherapy data using CWT_PATHWAY in order to split them post merger.
--Intention is for this view to mimic the output of CANCER__CWT_NATIONAL.CWT_RADIOTHERAPY and UNION together

CREATE OR REPLACE VIEW DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_RADIOTHERAPY_RFL_SPLIT
AS

--Pathway data does not have a 'Combined' pathway so need to pull data as CTE then create seperate 'Combined' version
WITH base_query 
AS(
SELECT
    TO_DATE(
        CONCAT(YEAR(DATE_TREATMENTSTARTDATE), '-', MONTH(DATE_TREATMENTSTARTDATE), '-', '01')) AS DATE_PERIOD,
    CASE
        WHEN MONTH(DATE_TREATMENTSTARTDATE) <= 3 THEN CONCAT(YEAR(DATE_TREATMENTSTARTDATE) - 1, '/', YEAR(DATE_TREATMENTSTARTDATE)-2000)
        ELSE CONCAT(YEAR(DATE_TREATMENTSTARTDATE), '/', YEAR(DATE_TREATMENTSTARTDATE)-1999)
    END AS FIN_YEAR,
    CASE
        WHEN MONTH(DATE_TREATMENTSTARTDATE) <= 3 THEN MONTH(DATE_TREATMENTSTARTDATE) + 9
        ELSE MONTH(DATE_TREATMENTSTARTDATE) - 3
    END AS FIN_MONTH_NUMBER,
    MONTHNAME(DATE_TREATMENTSTARTDATE) AS FIN_MONTH_NAME,

    --Main logic for identifying NMUH and RFL pre and post merger
    CASE 
        WHEN ORG_ACCOUNTABLETREATING_TRUST = 'RAP' OR ORG_ACCOUNTABLETREATING_SITE = 'RAL27' THEN 'RAP'
        WHEN ORG_ACCOUNTABLETREATING_TRUST = 'RAL' AND ORG_ACCOUNTABLETREATING_SITE != 'RAL27' THEN 'RAL'
    END AS ORGANISATION_CODE,

    CASE ORGANISATION_CODE
        WHEN 'RAP' THEN 'North Middlesex University Hospital NHS Trust'
        WHEN 'RAL' THEN 'Royal Free London NHS Foundation Trust'
    END AS ORGANISATION_NAME,

    --These fields come from the national table so if these values change in the national table, it gets reflected in this view
    nat.ORGANISATION_ICB_NAME,
    nat.ORGANISATION_ICB_CODE,
    nat.CANCER_ALLIANCE,
    nat.RADIOTHERAPY_NETWORK,
    
    CASE D31_FIRST
        WHEN TRUE THEN 'First'
        ELSE 'Subsequent'
    END AS CANCER_PATHWAY,
    SUM(PER_DENOMINATOR) AS NO_PATIENTS,
    SUM(PER_DENOMINATOR - PER_NUMERATOR) AS NO_COMPLIANT,
    SUM(PER_NUMERATOR) AS NO_BREACHES,

    nat.TARGET,

    NO_COMPLIANT AS D31_DAYS_WITHIN_31,
    SUM(CASE WHEN PER_VALUE >= 32 AND PER_VALUE <= 38 THEN 1 ELSE 0 END) AS D31_DAYS_32_TO_38,
    SUM(CASE WHEN PER_VALUE >= 39 AND PER_VALUE <= 48 THEN 1 ELSE 0 END) AS D31_DAYS_39_TO_48,
    SUM(CASE WHEN PER_VALUE >= 49 AND PER_VALUE <= 62 THEN 1 ELSE 0 END) AS D31_DAYS_49_TO_62,
    SUM(CASE WHEN PER_VALUE > 62 THEN 1 ELSE 0 END) AS D31_DAYS_MORE_THAN_62

FROM DEV__MODELLING.CANCER__CWT_PATHWAY.CWT_BASE base

--Join to get performance information (in a standardised format)
INNER JOIN DEV__MODELLING.CANCER__CWT_PATHWAY.CWT_PERFORMANCE perf
ON base.RECORD_ID = perf.RECORD_ID
AND perf.PER_METRIC = '31 Day'

--Join to seperate out First and Subsequent activity
INNER JOIN DEV__MODELLING.CANCER__CWT_PATHWAY.CWT_31DAYBREAKDOWN d31b
ON d31b.RECORD_ID = base.RECORD_ID

--Join to national data to get live ICB, Cancer Alliance, RT Network, and target info for RFL and NMUH
--Inner join here also prevents early RFL and NMUH data appearing in the output before the national data is updated
INNER JOIN (
    SELECT
        FIN_YEAR AS NAT_FIN_YEAR,
        FIN_MONTH_NUMBER AS NAT_FIN_MONTH_NUMBER,
        MAX(ORGANISATION_ICB_CODE) AS ORGANISATION_ICB_CODE,
        MAX(ORGANISATION_ICB_NAME) AS ORGANISATION_ICB_NAME,
        MAX(CANCER_ALLIANCE) AS CANCER_ALLIANCE,
        MAX(RADIOTHERAPY_NETWORK) AS RADIOTHERAPY_NETWORK,
        MAX(TARGET) AS TARGET,
    FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY
    WHERE ORGANISATION_CODE = 'RAL'
    GROUP BY ALL
) nat
ON FIN_YEAR = nat.NAT_FIN_YEAR
AND FIN_MONTH_NUMBER = nat.NAT_FIN_MONTH_NUMBER

WHERE ORGANISATION_CODE IN ('RAP', 'RAL')
--Filter logic for radiotherapy using ICD10 codes
AND CWT_MODALITY_CODE IN (4, 5, 6, 13)

GROUP BY ALL
)

--Get First and Subsequent data
SELECT * FROM base_query
--Allow for pre-Oct23 data for Subsequent only
WHERE (CANCER_PATHWAY = 'Subsequent' OR DATE_PERIOD >= '2023-10-01')

UNION ALL

--Get Combined data
SELECT 
    DATE_PERIOD, 
    FIN_YEAR, 
    FIN_MONTH_NUMBER, 
    FIN_MONTH_NAME, 
    ORGANISATION_CODE, 
    ORGANISATION_NAME, 
    ORGANISATION_ICB_NAME, 
    ORGANISATION_ICB_CODE, 
    CANCER_ALLIANCE, 
    RADIOTHERAPY_NETWORK, 
    'Combined' AS CANCER_PATHWAY, 
    SUM(NO_PATIENTS) AS NO_PATIENTS, 
    SUM(NO_COMPLIANT) AS NO_COMPLIANT, 
    SUM(NO_BREACHES) AS NO_BREACHES, 
    MAX(TARGET), 
    SUM(D31_DAYS_WITHIN_31) AS D31_DAYS_WITHIN_31, 
    SUM(D31_DAYS_32_TO_38) AS D31_DAYS_32_TO_38, 
    SUM(D31_DAYS_39_TO_48) AS D31_DAYS_39_TO_48, 
    SUM(D31_DAYS_49_TO_62) AS D31_DAYS_49_TO_62, 
    SUM(D31_DAYS_MORE_THAN_62) AS D31_DAYS_MORE_THAN_62
FROM base_query
WHERE DATE_PERIOD >= '2023-10-01'
GROUP BY ALL