create or replace view DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_RADIOTHERAPY(
	DATE_PERIOD,
	FIN_YEAR,
	FIN_MONTH_NUMBER,
	FIN_MONTH_NAME,
	ORGANISATION_CODE,
	ORGANISATION_NAME,
	ORGANISATION_ICB_NAME,
	ORGANISATION_ICB_CODE,
	CANCER_ALLIANCE,
	RADIOTHERAPY_NETWORK,
	CANCER_PATHWAY,
	NO_PATIENTS,
	NO_COMPLIANT,
	NO_BREACHES,
	TARGET,
	D31_DAYS_WITHIN_31,
	D31_DAYS_32_TO_38,
	D31_DAYS_39_TO_48,
	D31_DAYS_49_TO_62,
	D31_DAYS_MORE_THAN_62
) as 

SELECT 
    DATE_PERIOD,
    FIN_YEAR,
    FIN_MONTH_NUMBER,
    FIN_MONTH_NAME,
    ORGANISATION_CODE,
    ORGANISATION_NAME,
    ORGANISATION_ICB_NAME,
    ORGANISATION_ICB_CODE,
    CANCER_ALLIANCE,
    RADIOTHERAPY_NETWORK,
    CANCER_PATHWAY,
    NO_PATIENTS,
    NO_COMPLIANT,
    NO_BREACHES,
    TARGET,
    D31_DAYS_WITHIN_31,
    D31_DAYS_32_TO_38,
    D31_DAYS_39_TO_48,
    D31_DAYS_49_TO_62,
    D31_DAYS_MORE_THAN_62

    
FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY cwt

WHERE CANCER_TYPE = 'Radiotherapy'
AND STANDARD = '31 DAY'
AND ROW_POPULATION_TYPE = 'Provider'
--Filter out RFL and NMUH as they are included seperately below in order to split them post merger
AND ORGANISATION_CODE NOT IN ('RAL', 'RAP')

UNION ALL

SELECT * 
FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_RADIOTHERAPY_RFL_SPLIT;