
-------------------------------
-- Script to pull the GP-registered population counts to act as the reference population for age-sex standardised coverage calculations
----------------------------------
-- CERVICAL

CREATE OR REPLACE TABLE DEV__REPORTING.CANCER__SCREENING.GP_REGISTERED_REFERENCE_POPULATION_CERVICAL AS

SELECT 'Cervical' AS PROGRAMME
    ,GENDER
    ,AGE_BAND_5Y
    ,COUNT(*) AS COUNT 
    ,COUNT(*) / SUM(COUNT(*)) OVER () AS WEIGHTED_FACTOR

FROM REPORTING.OLIDS_PERSON_DEMOGRAPHICS.DIM_PERSON_DEMOGRAPHICS AS dem

INNER JOIN REPORTING.OLIDS_PERSON_STATUS.DIM_PERSON_SECONDARY_USE_ALLOWED AS opt -- apply opt outs 
ON dem.PERSON_ID = opt.PERSON_ID

WHERE IS_ACTIVE = TRUE
AND AGE BETWEEN 25 AND 64
AND GENDER = 'Female'
AND PRACTICE_CODE != 'Y03103' -- medicus select care is outside the OLIDs enterprise sharing agreement 

GROUP BY ALL;


-- BOWEL

CREATE OR REPLACE TABLE DEV__REPORTING.CANCER__SCREENING.GP_REGISTERED_REFERENCE_POPULATION_BOWEL AS

SELECT 'Bowel' AS PROGRAMME
    ,GENDER
    ,AGE_BAND_5Y
    ,COUNT(*) AS COUNT 
    ,COUNT(*) / SUM(COUNT(*)) OVER () AS WEIGHTED_FACTOR

FROM REPORTING.OLIDS_PERSON_DEMOGRAPHICS.DIM_PERSON_DEMOGRAPHICS AS dem

INNER JOIN REPORTING.OLIDS_PERSON_STATUS.DIM_PERSON_SECONDARY_USE_ALLOWED AS opt -- apply opt outs 
ON dem.PERSON_ID = opt.PERSON_ID

WHERE IS_ACTIVE = TRUE
AND AGE BETWEEN 50 AND 74
AND (GENDER =  'Female' OR GENDER =  'Male')
AND PRACTICE_CODE != 'Y03103' -- medicus select care is outside the OLIDs enterprise sharing agreement 

GROUP BY ALL ;