-----------------
-- create a table to look at the combined status of bowel and cervical cancer screening for eligible patients (females ages 50-64)
-----------------

CREATE OR REPLACE TABLE DEV__REPORTING.CANCER__SCREENING.OLIDS_SCREENING_DASHBOARD_SNAPSHOT_COMBINED_STATUS AS (

--WITH data AS (
SELECT DATE_DATA_REFRESH
    ,PERSON_ID
    ,PRACTICE_CODE
    ,PRACTICE_NAME
    ,PCN_NAME
    ,NEIGHBOURHOOD_REGISTERED
    ,BOROUGH_REGISTERED
    ,BOROUGH_RESIDENT_NCL_GROUP
    ,NEIGHBOURHOOD_RESIDENT_NCL_GROUP
    ,WARD_CODE
    ,WARD_RESIDENT_NCL_GROUP
    ,LATEST_GP_APPOINTMENT_ATTENDED
    ,ETHNICITY_SUBCATEGORY
    ,AGE_BAND_5Y
    ,SUM(CASE WHEN (SCREENING_PROGRAMME = 'Bowel' AND IS_UP_TO_DATE = 1) THEN 1 ELSE 0 END) AS BOWEL_UP_TO_DATE
    ,SUM(CASE WHEN (SCREENING_PROGRAMME = 'Cervical' AND IS_UP_TO_DATE = 1) THEN 1 ELSE 0 END)  AS CERVICAL_UP_TO_DATE
    ,CASE
        WHEN BOWEL_UP_TO_DATE >= 1 AND CERVICAL_UP_TO_DATE >= 1 THEN 'Up-to-date for both'
        WHEN BOWEL_UP_TO_DATE >= 1 AND CERVICAL_UP_TO_DATE = 0 THEN 'Up-to-date for bowel'
        WHEN BOWEL_UP_TO_DATE = 0 AND CERVICAL_UP_TO_DATE >= 1 THEN 'Up-to-date for cervical'
        WHEN BOWEL_UP_TO_DATE = 0 AND CERVICAL_UP_TO_DATE = 0 THEN 'Up-to-date for neither'
        ELSE 'error'
    END AS COMBINED_SCREENING_STATUS
    ,1 AS ELIGIBLE_COMBINED
    ,SECONDARY_USE_ALLOWED


FROM DEV__REPORTING.CANCER__SCREENING.OLIDS_SCREENING_DASHBOARD_SNAPSHOT

WHERE GENDER = 'Female' -- only pull eligible patients 
AND AGE_BAND_5Y IN ('50-54', '55-59', '60-64')

GROUP BY ALL
);

select *
from DEV__REPORTING.CANCER__SCREENING.OLIDS_SCREENING_DASHBOARD_SNAPSHOT_COMBINED_STATUS