create or replace view REPORTING.CANCER__ARG.CWT_SUMMARY_NCL(
	PROVIDER_CODE,
	PROVIDER_NAME,
	STANDARD,
	DATE,
	FIN_YEAR,
	FIN_MONTH_NAME,
	ACTIVITY_TOTAL,
	ACTIVITY_COMPLIANT,
	ACTIVITY_BREACHES,
	ACTIVITY_PERFORMANCE,
	PREV_PERFORMANCE,
	CHANGE_IN_PERFORMANCE,
	TRAJECTORY_TOTAL,
	TRAJECTORY_COMPLIANT,
	TRAJECTORY_BREACHES,
	TRAJECTORY_PERFORMANCE,
	TARGET,
	TARGET_ASPIRATION,
	TRAJECTORY_GAP,
	TARGET_GAP,
	ASPIRATION_GAP
) COMMENT='Table to populate monthly CWT performance summary.\\nContact: jake.kealey@nhs.net'
 as

WITH BASE_PERFORMANCE AS (
    --FDS
    SELECT 
        STANDARD,
        DATE,
        FIN_YEAR,
        FIN_MONTH_NAME,
        FDS_PROVIDER_CODE AS PROVIDER_CODE,
        FDS_PROVIDER_NAME AS PROVIDER_NAME,
        SUM(NO_PATIENTS) AS ACTIVITY_TOTAL,
        SUM(NO_PATIENTS - BREACHES) AS ACTIVITY_COMPLIANT,
        SUM(BREACHES) AS ACTIVITY_BREACHES
    FROM MODELLING.CANCER__CWT_ALLIANCE.TRUST__FDS
    GROUP BY ALL
    
    UNION ALL
    
    --31 Day
    SELECT 
        STANDARD,
        DATE,
        FIN_YEAR,
        FIN_MONTH_NAME,
        PROVIDER_CODE AS PROVIDER_CODE,
        PROVIDER_NAME AS PROVIDER_NAME,
        SUM(NO_TREATED) AS ACTIVITY_TOTAL,
        SUM(NO_TREATED - BREACHES) AS ACTIVITY_COMPLIANT,
        SUM(BREACHES) AS ACTIVITY_BREACHES,
    FROM MODELLING.CANCER__CWT_ALLIANCE.TRUST__31_DAY

            -- filter out activty not included in performance - BG 19/12/25
        WHERE           -- First treatment: Event Type IN (01, 07, 12) AND Modality <> 98
         ( (TREATMENT_STAGE = 'First Treatment'
           AND TREATMENT_MODALITY <> 'All treatment declined')
          OR
          -- Subsequent: Event Type IN (02–06, 08–11) AND Modality NOT IN (07, 08, 09, 98)
          (TREATMENT_STAGE = 'Subsequent'
           AND TREATMENT_MODALITY NOT IN (
                'Specialist Palliative Care',
                'Active Monitoring (excluding Non-Specialist Palliative Care)',
                'Non-Specialist Palliative Care (excluding Active Monitoring)',
                'All treatment declined'
           )))  
           --end additions - BG 19/12/25
    
    
    GROUP BY ALL
    
    UNION ALL
    
    --62 Day
    SELECT 
        STANDARD,
        DATE,
        FIN_YEAR,
        FIN_MONTH_NAME,
        ACCOUNTABLE_62_DAY_PROVIDER_CODE AS PROVIDER_CODE,
        ACCOUNTABLE_62_DAY_PROVIDER_NAME AS PROVIDER_NAME,
        SUM(NO_PATIENTS) AS ACTIVITY_TOTAL,
        SUM(NO_PATIENTS - BREACHES) AS ACTIVITY_COMPLIANT,
        SUM(BREACHES) AS ACTIVITY_BREACHES
    FROM MODELLING.CANCER__CWT_ALLIANCE.TRUST__62_DAY
    GROUP BY ALL
),

PERFORMANCE_WITH_TRAJ AS (

    SELECT 
        bp.*,
        DENOMINATOR AS TRAJECTORY_TOTAL,
        NUMERATOR AS TRAJECTORY_COMPLIANT
    FROM BASE_PERFORMANCE bp

    --Join to get trajectory data
    LEFT JOIN MODELLING.CANCER__CCO.CANCER_TRAJECTORY traj
    ON bp.DATE = traj.DATE_FULL
    AND bp.PROVIDER_CODE = traj.PROVIDER_CODE
    AND bp.STANDARD = traj.STANDARD
)
    
SELECT 
    sp.* EXCLUDE (TRAJECTORY_TOTAL, TRAJECTORY_COMPLIANT),
    ACTIVITY_COMPLIANT / ACTIVITY_TOTAL AS ACTIVITY_PERFORMANCE,
    LAG(ACTIVITY_PERFORMANCE) OVER (PARTITION BY sp.STANDARD, sp.PROVIDER_CODE ORDER BY sp.DATE) AS PREV_PERFORMANCE,
    ACTIVITY_PERFORMANCE - PREV_PERFORMANCE AS CHANGE_IN_PERFORMANCE,
    TRAJECTORY_TOTAL,
    TRAJECTORY_COMPLIANT,
    TRAJECTORY_TOTAL - TRAJECTORY_COMPLIANT AS TRAJECTORY_BREACHES,
    TRAJECTORY_COMPLIANT / TRAJECTORY_TOTAL AS TRAJECTORY_PERFORMANCE,
    cwt_t.TARGET,
    cwt_t_a.TARGET AS TARGET_ASPIRATION,
    --Derive other required columns
    CASE 
        WHEN ACTIVITY_PERFORMANCE >= TRAJECTORY_PERFORMANCE THEN NULL
        ELSE CEIL((ACTIVITY_TOTAL * (TRAJECTORY_COMPLIANT/TRAJECTORY_TOTAL)) - ACTIVITY_COMPLIANT)
    END AS TRAJECTORY_GAP,

    CASE 
        WHEN ACTIVITY_PERFORMANCE >= cwt_t.TARGET THEN NULL
        ELSE CEIL((ACTIVITY_TOTAL * cwt_t.TARGET) - ACTIVITY_COMPLIANT)
    END AS TARGET_GAP,

    CASE 
        WHEN ACTIVITY_PERFORMANCE >= TARGET_ASPIRATION THEN NULL
        ELSE CEIL((ACTIVITY_TOTAL * TARGET_ASPIRATION) - ACTIVITY_COMPLIANT)
    END AS ASPIRATION_GAP

--Split base data by trust and NCL overall
FROM (
    --Provider data
    --Aggregate to combine RFL and NMUH
    SELECT
        org.PROVIDER_CODE,
        org.PROVIDER_SHORTHAND AS PROVIDER_SHORTHAND,
        STANDARD,
        DATE,
        FIN_YEAR,
        FIN_MONTH_NAME,
        SUM(ACTIVITY_TOTAL) AS ACTIVITY_TOTAL,
        SUM(ACTIVITY_COMPLIANT) AS ACTIVITY_COMPLIANT,
        SUM(ACTIVITY_BREACHES) AS ACTIVITY_BREACHES,
        SUM(TRAJECTORY_TOTAL) AS TRAJECTORY_TOTAL,
        SUM(TRAJECTORY_COMPLIANT) AS TRAJECTORY_COMPLIANT
    FROM PERFORMANCE_WITH_TRAJ p
    LEFT JOIN MODELLING.LOOKUP_NCL.NCL_PROVIDER org
    ON p.PROVIDER_CODE = org.REPORTING_CODE
    --WHERE p.PROVIDER_CODE IN ('RAL', 'RAN', 'RKE', 'RRV')
    GROUP BY ALL

    UNION ALL

    --NCL data
    SELECT 
        'QMJ' AS PROVIDER_CODE,
        'NCL' AS PROVIDER_NAME,
        STANDARD,
        DATE,
        FIN_YEAR,
        FIN_MONTH_NAME,
        SUM(ACTIVITY_TOTAL) AS ACTIVITY_TOTAL,
        SUM(ACTIVITY_COMPLIANT) AS ACTIVITY_COMPLIANT,
        SUM(ACTIVITY_BREACHES) AS ACTIVITY_BREACHES,
        SUM(TRAJECTORY_TOTAL) AS TRAJECTORY_TOTAL,
        SUM(TRAJECTORY_COMPLIANT) AS TRAJECTORY_COMPLIANT
    FROM PERFORMANCE_WITH_TRAJ
    GROUP BY ALL
) sp

--Join to get constitutional targets
LEFT JOIN MODELLING.CANCER__REF.CWT_STANDARD_TARGETS cwt_t
ON sp.STANDARD = cwt_t.STANDARD
AND sp.FIN_YEAR = cwt_t.FIN_YEAR

--Join to get aspirational targets
LEFT JOIN (
    --Subquery to only pull the latest targets
    SELECT * 
    FROM MODELLING.CANCER__REF.CWT_STANDARD_TARGETS
    QUALIFY FIN_YEAR = MAX(FIN_YEAR) OVER (PARTITION BY STANDARD)
)cwt_t_a
ON CONCAT(sp.STANDARD, ' Aspiration') = cwt_t_a.STANDARD

WHERE sp.FIN_YEAR >= '2024/25'

ORDER BY sp.DATE, sp.PROVIDER_CODE, sp.STANDARD;