create or replace view REPORTING.CANCER__ARG.CWT_HIGHLIGHTS(
	VLOOKUP_KEY,
	CATEGORY,
	PROVIDER_CODE,
	PROVIDER_SHORTHAND,
	STANDARD,
	DATE,
	CANCER_TYPE,
	CANCER_TYPE_SHORT,
	ACTIVITY_TOTAL,
	ACTIVITY_BREACHES,
	RANK_BREACHES,
	ACTIVITY_PERFORMANCE,
	PREV_PERFORMANCE,
	CHANGE_IN_PERFORMANCE,
	SIGNIFICANT_ACTIVITY,
	VLOOKUP_SUFFIX,
	ASPIRATION_BREAST_AND_SKIN
) COMMENT='CWT table to flag the cancer types with the most breaches, biggest change in performance, groups of interest.'
 as

WITH MERGE_TRUSTS AS (
SELECT
    org.PROVIDER_CODE, 
    org.PROVIDER_SHORTHAND, 
    STANDARD, 
    DATE, 
    CANCER_TYPE, 
    CANCER_TYPE_SHORT, 
    SUM(ACTIVITY_TOTAL) AS ACTIVITY_TOTAL, 
    SUM(ACTIVITY_BREACHES) AS ACTIVITY_BREACHES,
    SUM(ACTIVITY_COMPLIANT) AS ACTIVITY_COMPLIANT

FROM REPORTING.CANCER__ARG.CWT_SUMMARY_BY_CANCER_TYPE arg

LEFT JOIN MODELLING.LOOKUP_NCL.NCL_PROVIDER org
ON arg.PROVIDER_CODE = org.REPORTING_CODE
AND org.ROW_TYPE = 'trust'

WHERE org.PROVIDER_CODE IN ('RAL', 'RRV', 'RKE')
GROUP BY ALL
),

BASE_QUERY AS (
SELECT
    PROVIDER_CODE, 
    PROVIDER_SHORTHAND, 
    STANDARD, 
    DATE, 
    CANCER_TYPE, 
    CANCER_TYPE_SHORT, 
    ACTIVITY_TOTAL, 
    ACTIVITY_BREACHES, 
    RANK() OVER (PARTITION BY PROVIDER_CODE, STANDARD, DATE ORDER BY ACTIVITY_BREACHES DESC, ACTIVITY_TOTAL, CANCER_TYPE_SHORT) AS RANK_BREACHES,
    ACTIVITY_COMPLIANT/ACTIVITY_TOTAL AS ACTIVITY_PERFORMANCE,
    LAG(ACTIVITY_PERFORMANCE, 12) OVER (PARTITION BY PROVIDER_CODE, STANDARD ORDER BY DATE) AS PREV_PERFORMANCE,
    ACTIVITY_PERFORMANCE - PREV_PERFORMANCE AS CHANGE_IN_PERFORMANCE
    
    FROM MERGE_TRUSTS
),
WITH_SIGNIFICANCE AS (
    SELECT *,
    SUM(ACTIVITY_TOTAL) OVER (PARTITION BY PROVIDER_CODE, STANDARD, DATE) * 0.05 AS SIGNIFICANT_ACTIVITY
    FROM BASE_QUERY
)

SELECT
    CONCAT(CATEGORY, '-', STANDARD, '-', PROVIDER_SHORTHAND, '-', VLOOKUP_SUFFIX) AS VLOOKUP_KEY,
    *
FROM (
    
    --Top 5 breaches
    SELECT 'Most Breaches' AS CATEGORY, *, TO_CHAR(RANK_BREACHES) AS VLOOKUP_SUFFIX 
    FROM WITH_SIGNIFICANCE
    WHERE RANK_BREACHES <= 5
    
    UNION ALL
    
    --Most improved
    SELECT 'Most Improved' AS CATEGORY, *, 'MI' AS VLOOKUP_SUFFIX 
    FROM WITH_SIGNIFICANCE
    WHERE ACTIVITY_TOTAL >= SIGNIFICANT_ACTIVITY
    QUALIFY CHANGE_IN_PERFORMANCE = MAX(CHANGE_IN_PERFORMANCE) OVER (PARTITION BY PROVIDER_CODE, STANDARD, DATE)
    
    UNION ALL
    
    --Least improved
    SELECT 'Least Improved' AS CATEGORY, *, 'LI' AS VLOOKUP_SUFFIX 
    FROM WITH_SIGNIFICANCE
    WHERE ACTIVITY_TOTAL >= SIGNIFICANT_ACTIVITY
    QUALIFY CHANGE_IN_PERFORMANCE = MIN(CHANGE_IN_PERFORMANCE) OVER (PARTITION BY PROVIDER_CODE, STANDARD, DATE)

    UNION ALL BY NAME

    --Breast and Skin
    SELECT
        'Breast and Skin' AS CATEGORY, 
        ws.*, 
        ws.CANCER_TYPE AS VLOOKUP_SUFFIX,
        tar.TARGET AS ASPIRATION_BREAST_AND_SKIN
    FROM WITH_SIGNIFICANCE ws
    LEFT JOIN MODELLING.CANCER__REF.CWT_STANDARD_TARGETS tar
    ON tar.STANDARD = 'FDS Aspiration (Breast and Skin)'
    WHERE CANCER_TYPE IN ('Breast', 'Skin')
)
ORDER BY 
    DATE, 
    PROVIDER_CODE, 
    STANDARD, 
    CASE CATEGORY 
        WHEN 'Most Breaches' THEN 1 
        WHEN 'Most Improved' THEN 2 
        WHEN 'Least Improved' THEN 3 
        WHEN 'Breast and Skin' THEN 4
        ELSE 9 
    END, 
    RANK_BREACHES
;