create or replace view REPORTING.CANCER__ARG.CWT_TREND_NCL(
	PROVIDER_CODE,
	PROVIDER_NAME,
	STANDARD,
	DATE,
	FIN_YEAR,
	FIN_MONTH_NAME,
	ACTIVITY_TOTAL,
	ACTIVITY_COMPLIANT,
	ACTIVITY_BREACHES,
	ACTIVITY_PERFORMANCE,
	TARGET,
	TARGET_ASPIRATION,
	TRAJECTORY_PERFORMANCE
) COMMENT='Table to populate trend CWT performance.\nContact: jake.kealey@nhs.net'
 as

SELECT
    PROVIDER_CODE, PROVIDER_NAME,
    STANDARD, DATE, FIN_YEAR, FIN_MONTH_NAME,
    ACTIVITY_TOTAL, ACTIVITY_COMPLIANT, ACTIVITY_BREACHES,
    ACTIVITY_PERFORMANCE, TARGET, TARGET_ASPIRATION, TRAJECTORY_PERFORMANCE
FROM REPORTING.CANCER__ARG.CWT_SUMMARY_NCL
ORDER BY PROVIDER_CODE, STANDARD, DATE;