create or replace view REPORTING.CANCER__ARG.PTL_SUMMARY(
	REPORTING_DATE,
	ORG_CODE,
	ORG_NAME,
	TOTAL_PTL,
	PTL_DAYS_MORE_THAN_28,
	PTL_DAYS_MORE_THAN_28_PERCENT,
	PTL_DAYS_MORE_THAN_62,
	PTL_DAYS_MORE_THAN_62_PERCENT,
	CHANGE_TOTAL_PTL,
	CHANGE_PTL_DAYS_MORE_THAN_28,
	CHANGE_PTL_DAYS_MORE_THAN_28_PERCENT,
	CHANGE_PTL_DAYS_MORE_THAN_62,
	CHANGE_PTL_DAYS_MORE_THAN_62_PERCENT
) COMMENT='Summary of the cancer PTL state.\nContact:jake.kealey@nhs.net'
 as

SELECT
    REPORTING_DATE,
    ORG_CODE,
    COALESCE(org.PROVIDER_SHORTHAND, ptl.ROW_TYPE) AS ORG_NAME,
    TOTAL_PTL,
    TOTAL_PTL - DAYS_0_TO_28 AS PTL_DAYS_MORE_THAN_28,
    DIV0(PTL_DAYS_MORE_THAN_28, TOTAL_PTL) AS PTL_DAYS_MORE_THAN_28_PERCENT,
    TOTAL_PTL - DAYS_0_TO_62 AS PTL_DAYS_MORE_THAN_62,
    DIV0(PTL_DAYS_MORE_THAN_62, TOTAL_PTL) AS PTL_DAYS_MORE_THAN_62_PERCENT,
    
    TOTAL_PTL - (LAG(TOTAL_PTL) OVER (PARTITION BY ORG_NAME ORDER BY REPORTING_DATE)) AS CHANGE_TOTAL_PTL,
    PTL_DAYS_MORE_THAN_28 - (LAG(PTL_DAYS_MORE_THAN_28) OVER (PARTITION BY ORG_NAME ORDER BY REPORTING_DATE)) AS CHANGE_PTL_DAYS_MORE_THAN_28,
    PTL_DAYS_MORE_THAN_28_PERCENT - (LAG(PTL_DAYS_MORE_THAN_28_PERCENT) OVER (PARTITION BY ORG_NAME ORDER BY REPORTING_DATE)) AS CHANGE_PTL_DAYS_MORE_THAN_28_PERCENT,
    PTL_DAYS_MORE_THAN_62 - (LAG(PTL_DAYS_MORE_THAN_62) OVER (PARTITION BY ORG_NAME ORDER BY REPORTING_DATE)) AS CHANGE_PTL_DAYS_MORE_THAN_62,
    PTL_DAYS_MORE_THAN_62_PERCENT - (LAG(PTL_DAYS_MORE_THAN_62_PERCENT) OVER (PARTITION BY ORG_NAME ORDER BY REPORTING_DATE)) AS CHANGE_PTL_DAYS_MORE_THAN_62_PERCENT
    
FROM (
    --NCL Trusts
    SELECT
        'Provider' AS ROW_TYPE,
        REPORTING_DATE,
        ORG_CODE,
        SUM(TOTAL_PTL) AS TOTAL_PTL,
        SUM(DAYS_0_TO_28) AS DAYS_0_TO_28,
        SUM(DAYS_0_TO_62) AS DAYS_0_TO_62
    
    FROM MODELLING.CANCER__CCO.CANCER_PTL
    WHERE CANCER_ALLIANCE LIKE 'North Central London'

    GROUP BY ALL

    UNION ALL

    --London
    SELECT
        'London' AS ROW_TYPE,
        REPORTING_DATE,
        NULL,
        SUM(TOTAL_PTL) AS TOTAL_PTL,
        SUM(DAYS_0_TO_28) AS DAYS_0_TO_28,
        SUM(DAYS_0_TO_62) AS DAYS_0_TO_62
        
    
    FROM MODELLING.CANCER__CCO.CANCER_PTL
    WHERE REGION = 'London'
    GROUP BY ALL

    UNION ALL

    --England
    SELECT
        'England' AS ROW_TYPE,
        REPORTING_DATE,
        NULL,
        SUM(TOTAL_PTL) AS TOTAL_PTL,
        SUM(DAYS_0_TO_28) AS DAYS_0_TO_28,
        SUM(DAYS_0_TO_62) AS DAYS_0_TO_62
    
    FROM MODELLING.CANCER__CCO.CANCER_PTL
    GROUP BY ALL
) ptl

LEFT JOIN MODELLING.LOOKUP_NCL.NCL_PROVIDER org
ON org.REPORTING_CODE = ptl.ORG_CODE

ORDER BY REPORTING_DATE DESC, ptl.ROW_TYPE, ORG_NAME;