create or replace view REPORTING.CANCER__ARG.PTL_BY_CANCER_TYPE(
	REPORTING_DATE,
	ORG_CODE,
	CANCER_TYPE,
	CANCER_TYPE_SHORT,
	TOTAL_PTL,
	DAYS_MORE_THAN_62
) COMMENT='Summary of the cancer PTL by cancer type.\nContact:jake.kealey@nhs.net'
 as

SELECT 
    REPORTING_DATE, 
    ORG_CODE, 
    ctl.CANCER_TYPE,
    ctl.CANCER_TYPE_SHORT,
    SUM(TOTAL_PTL) AS TOTAL_PTL,
    SUM(DAYS_MORE_THAN_62) AS DAYS_MORE_THAN_62
    
FROM MODELLING.CANCER__CCO.CANCER_PTL ptl

LEFT JOIN MODELLING.CANCER__REF.CANCER_TYPE_LOOKUP ctl
ON ptl.CANCER_TYPE = ctl.CANCER_TYPE_SOURCE

WHERE CANCER_ALLIANCE = 'North Central London'
AND ptl.CANCER_TYPE IS NOT NULL

GROUP BY ALL

QUALIFY REPORTING_DATE = MAX(REPORTING_DATE) OVER ()
ORDER BY REPORTING_DATE, ORG_CODE, DAYS_MORE_THAN_62 DESC;