create or replace view REPORTING.CANCER__ARG.RANKING(
	DATE_PERIOD,
	FIN_YEAR,
	FIN_MONTH_NAME,
	ORGANISATION_CODE,
	ORGANISATION_NAME,
	ORGANISATION_NAME_SHORT,
	ORGANISATION_ICB_CODE,
	ORGANISATION_ICB_NAME,
	ORGANISATION_REGION_CODE,
	ORGANISATION_REGION_NAME,
	CANCER_ALLIANCE,
	STANDARD,
	CANCER_TYPE,
	NO_PATIENTS,
	NO_COMPLIANT,
	STANDARD_PERFORMANCE,
	TARGET,
	SIGNIFICANT_ACTIVITY,
	RANK_PERFORMANCE,
	RANK_DENOMINATOR,
	UNADJUSTED_RANK_PERFORMANCE,
	UNADJUSTED_RANK_DENOMINATOR,
	NO_PATIENTS_ENGLAND
) COMMENT='View for the ranking output for the ARG publication.\nContact: jake.kealey@nhs.net'
 as

SELECT * FROM MODELLING.CANCER__CWT_NATIONAL.RANKING;