create or replace view REPORTING.CANCER__ARG.RANKING__BY_TRUST(
	DATE_PERIOD,
	RANK_DENOMINATOR,
	STANDARD,
	PROVIDER_NAME,
	STANDARD_PERFORMANCE,
	RANK_PERFORMANCE,
	PERFORMANCE_LAST_YEAR,
	RANK_LAST_YEAR
) COMMENT='View for the ranking output for the ARG publication.\nContact: jake.kealey@nhs.net'
 as

SELECT 
DATE_PERIOD,
UNADJUSTED_RANK_DENOMINATOR AS RANK_DENOMINATOR,

STANDARD,
PROVIDER_SHORTHAND AS PROVIDER_NAME,
STANDARD_PERFORMANCE,
UNADJUSTED_RANK_PERFORMANCE AS RANK_PERFORMANCE,

LAG(STANDARD_PERFORMANCE, 12) OVER (PARTITION BY ORGANISATION_CODE, STANDARD ORDER BY DATE_PERIOD) AS PERFORMANCE_LAST_YEAR,
LAG(UNADJUSTED_RANK_PERFORMANCE, 12) OVER (PARTITION BY ORGANISATION_CODE, STANDARD ORDER BY DATE_PERIOD) AS RANK_LAST_YEAR

FROM MODELLING.CANCER__CWT_NATIONAL.RANKING rnk

LEFT JOIN MODELLING.LOOKUP_NCL.NCL_PROVIDER org
ON org.REPORTING_CODE = rnk.ORGANISATION_CODE

WHERE CANCER_TYPE = 'Overall'
AND ORGANISATION_CODE IN ('RAL', 'RAN', 'RRV', 'RKE')

ORDER BY 
    DATE_PERIOD, 
    CASE STANDARD
        WHEN 'FDS' THEN 1
        WHEN '31 Day' THEN 2
        WHEN '62 Day' THEN 3
        ELSE 4
    END, 
    ORGANISATION_NAME_SHORT;