create or replace view REPORTING.CANCER__ARG.RANKING__BY_CANCER_ALLIANCE(
	DATE_PERIOD,
	RANK_DENOMINATOR,
	STANDARD,
	CANCER_ALLIANCE,
	STANDARD_PERFORMANCE,
	RANK_PERFORMANCE,
	PERFORMANCE_LAST_YEAR,
	RANK_LAST_YEAR
) COMMENT='View for the ranking output for the ARG publication.\nContact: jake.kealey@nhs.net'
 as

SELECT 
DATE_PERIOD,
RANK_DENOMINATOR,

STANDARD,
CANCER_ALLIANCE,
STANDARD_PERFORMANCE,
RANK_PERFORMANCE,

LAG(STANDARD_PERFORMANCE, 12) OVER (PARTITION BY CANCER_ALLIANCE, STANDARD ORDER BY DATE_PERIOD) AS PERFORMANCE_LAST_YEAR,
LAG(RANK_PERFORMANCE, 12) OVER (PARTITION BY CANCER_ALLIANCE, STANDARD ORDER BY DATE_PERIOD) AS RANK_LAST_YEAR

FROM MODELLING.CANCER__CWT_NATIONAL.RANKING__BY_CANCER_ALLIANCE
WHERE CANCER_TYPE = 'Overall'
AND CANCER_ALLIANCE IN ('North Central London', 'North East London', 'South East London', 'West London')

ORDER BY 
    DATE_PERIOD, 
    CASE STANDARD
        WHEN 'FDS' THEN 1
        WHEN '31 Day' THEN 2
        WHEN '62 Day' THEN 3
        ELSE 4
    END, 
    CANCER_ALLIANCE;