create or replace dynamic table DEV__MODELLING.FINGERTIPS.INDICATOR_DATA_ICB(
	INDICATOR_ID,
	INDICATOR_NAME,
	ICB_CODE,
	ICB_NAME,
	VALUE,
	VALUE_UNIT,
	VALUE_TYPE,
	NUMERATOR,
	DENOMINATOR,
	DATE_INDICATOR,
	DATE_INDICATOR_TYPE,
	DATE_INDICATOR_RANGE,
	DATE_INDICATOR_SORTABLE
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = NCL_ANALYTICS_XS
 COMMENT='ICB level Fingertips data (NCL ICB only)\nContact: jake.kealey@nhs.net'
 as

SELECT
    iaa.INDICATOR_ID,
    iaa.INDICATOR_NAME,
    iaa.AREA_CODE AS ICB_CODE,
    iaa.AREA_NAME AS ICB_NAME,
    iaa.VALUE,
    iaa.VALUE_UNIT,
    iaa.VALUE_TYPE,
    iaa.NUMERATOR,
    iaa.DENOMINATOR,
    iaa.DATE_INDICATOR,
    iaa.DATE_INDICATOR_TYPE,
    iaa.DATE_INDICATOR_RANGE,
    iaa.DATE_INDICATOR_SORTABLE

FROM DEV__MODELLING.FINGERTIPS.INDICATOR_DATA_ALL_AREAS iaa

--Filter to ICB data
WHERE iaa.AREA_ID = 221
AND iaa.AREA_CODE = 'E54000028';