-- View which combines cleaned local screening data with lung screening data.
-- Contact: eric.pinto@nhs.net

create or replace view DEV__PUBLISHED_REPORTING__SECONDARY_USE.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__LOCAL(
	REGION_NAME,
	PCN_NAME,
	BOROUGH,
	PRACTICE_CODE,
	PRACTICE_NAME,
	DEPRIVATION_QUINTILE,
	POPULATION_COUNT,
	PARENT_COUNT,
	DATE_FULL,
	COHORT_AGE_RANGE,
	COHORT_DESCRIPTION,
	DENOMINATOR_NAME,
	ACCEPTABLE,
	ACHIEVABLE,
	PROGRAMME,
	IS_MAX_DATE
) COMMENT='VIEW that pulls Local Screening Data for use in PBI Primary Care Dashboard. Query to pull only data from Latest Screening Date minus 3 Years'
 as

SELECT 
*  
FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__LOCAL
WHERE DATE_FULL IS NULL
    OR (
    DATE_FULL BETWEEN
    DATEADD(YEAR, -3, (SELECT MAX(DATE_FULL) FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__LOCAL))
    AND (SELECT MAX(DATE_FULL) FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__LOCAL)
    );