-- View to provide Screening Benchmarking. This table combines aggregated Borough and NCL level data with National level data.
-- Contact: eric.pinto@nhs.net

create or replace view DEV__PUBLISHED_REPORTING__SECONDARY_USE.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__BENCHMARKING(
	REGION_NAME,
	PROGRAMME,
	DATE_FULL,
	COHORT_AGE_RANGE,
	COHORT_DESCRIPTION,
	DENOMINATOR_NAME,
	DENOMINATOR,
	NUMERATOR,
	ACCEPTABLE,
	ACHIEVABLE,
	IS_MAX_DATE,
	REGION_ORDER
) COMMENT='VIEW that pulls Benchmarking Screening Data for use in PBI Primary Care Dashboard. Query to pull only data from Latest Screening Date minus 3 Years'
 as

SELECT 
*  
FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__BENCHMARKING
WHERE DATE_FULL IS NULL
    OR (
    DATE_FULL BETWEEN
    DATEADD(YEAR, -3, (SELECT MAX(DATE_FULL) FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__BENCHMARKING))
    AND (SELECT MAX(DATE_FULL) FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__SCREENING__BENCHMARKING)
    );
