-- View that SELECTs Population Health data for use in the Primary Care Dashboard. UNION Social Prescribing Data as they are joined in the Dashboard.
-- Contact: eric.pinto@nhs.net

create or replace view DEV__PUBLISHED_REPORTING__SECONDARY_USE.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__FINGERTIPS__INDICATOR_DATA(
	INDICATOR_ID,
	INDICATOR_NAME,
	AREA_TYPE,
	AREA_NAME,
	AREA_CODE,
	GP_PRACTICE_DESC,
	PCN_CODE,
	PCN_NAME,
	BOROUGH_NAME,
	VALUE,
	VALUE_UNIT,
	VALUE_TYPE,
	NUMERATOR,
	DENOMINATOR,
	DATE_INDICATOR,
	DATE_INDICATOR_TYPE,
	DATE_INDICATOR_RANGE,
	DATE_INDICATOR_SORTABLE,
	IS_NCL,
	IS_LONDON,
	IS_ENGLAND,
	IS_MAX_DATE,
	MAX_DATE
) COMMENT='View that SELECTs Population Health data for use in the Primary Care Dashboard. UNION Social Prescribing Data as they are joined in the Dashboard.'
 as

SELECT * FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__FINGERTIPS__INDICATOR_DATA

UNION ALL 

SELECT * FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__EMIS__SOCIAL_PRESCRIBING;
