-- View to prepare FIT data for use in the Primary Care Dashboard.
-- Contact: eric.pinto@nhs.net

create or replace view DEV__PUBLISHED_REPORTING__SECONDARY_USE.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__EMIS__FIT(
	PRACTICE_CODE,
	PRACTICE_NAME,
	DEPRIVATION_QUINTILE,
	PCN_NAME,
	BOROUGH,
	POPULATION_COUNT,
	PARENT_COUNT,
	DATE_FULL,
	TIME_PERIOD,
	YEAR_QUARTER_SORT,
	DATE_TYPE,
	IS_MAX_DATE,
	TIMESTAMP
) COMMENT='View to SELECT FIT data for use in the Primary Care Dashboard.'
 as
SELECT *
FROM DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__EMIS__FIT;
