-- Dynamic table to prepare Population Health data for use in the Primary Care Dashboard.
-- Contact: eric.pinto@nhs.net

CREATE OR REPLACE DYNAMIC TABLE DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__FINGERTIPS__INDICATOR_DATA(
    
    INDICATOR_ID,
	INDICATOR_NAME,
	GP_PRACTICE_CODE,
	GP_PRACTICE_DESC,
	PCN_CODE,
	PCN_NAME,
	BOROUGH_NAME,
	VALUE,
	VALUE_UNIT,
	VALUE_TYPE,
	NUMERATOR,
	DENOMINATOR,
	DATE_INDICATOR,
	DATE_INDICATOR_TYPE,
	DATE_INDICATOR_RANGE,
	DATE_INDICATOR_SORTABLE,
    IS_MAX_DATE,
    MAX_DATE
    
    

) target_lag = '2 hours' refresh_mode = FULL initialize = ON_CREATE warehouse = NCL_ANALYTICS_XS
 COMMENT='Dynamic table to prepare Population Health data for use in the Primary Care Dashboard.'
 as

-- CTE to enable retrieving past 3 years of data from individual Indicators
WITH Original AS (
    SELECT 
    INDICATOR_ID,
	INDICATOR_NAME,
	PRACTICE_CODE AS GP_PRACTICE_CODE,
	PRACTICE_NAME AS GP_PRACTICE_DESC,
	PCN_CODE,
	PCN_NAME,
	BOROUGH_NAME,
	VALUE,
	VALUE_UNIT,
	VALUE_TYPE,
	NUMERATOR,
	DENOMINATOR,
	DATE_INDICATOR,
	DATE_INDICATOR_TYPE,
	DATE_INDICATOR_RANGE,
	DATE_INDICATOR_SORTABLE,
        
        -- Boolean to get max date for each Indicator
        CASE 
            WHEN DATE_INDICATOR_SORTABLE = MAX(DATE_INDICATOR_SORTABLE) OVER (PARTITION BY INDICATOR_NAME)
            THEN TRUE
            ELSE FALSE
        END AS IS_MAX_DATE,

        -- Actual max date for each Indicator (year only)
        TO_VARCHAR(LEFT(MAX(DATE_INDICATOR_SORTABLE) OVER (PARTITION BY INDICATOR_NAME), 4)) AS MAX_DATE

    FROM DEV__MODELLING.FINGERTIPS.INDICATOR_DATA_GP
    WHERE INDICATOR_ID IN (276, 91280, 91337, 91355, 91357, 91845, 92588, 93553, 94136)
)

SELECT *
FROM ORIGINAL
-- WHERE clause to get the previous 3 years of data for each indicator separately
WHERE CAST(LEFT(DATE_INDICATOR_SORTABLE, 4) AS NUMBER) >= MAX_DATE - 3;