-- This pulls the most recent 4 financial years ofdata from the CWT National Monthly Modelling table
-- Contact: eric.pinto@nhs.net

create or replace dynamic table DEV__REPORTING.CANCER__CWT_SUMMARY_REPORTS.CWT_NATIONAL_DASHBOARD(
	ROW_POPULATION_TYPE,
	DATE_PERIOD,
	FIN_YEAR,
	FIN_MONTH_NUMBER,
	FIN_MONTH_NAME,
	ORGANISATION_TYPE,
	ORGANISATION_CODE,
	ORGANISATION_KEY,
	ORGANISATION_NAME,
	ORGANISATION_NAME_SHORT,
	ORGANISATION_REGION_CODE,
	ORGANISATION_REGION_NAME,
	ORGANISATION_ICB_CODE,
	ORGANISATION_ICB_NAME,
	CANCER_ALLIANCE,
	RADIOTHERAPY_NETWORK,
	STANDARD,
	CANCER_TYPE,
	CANCER_TYPE_SUBCATEGORY,
	CANCER_PATHWAY,
	CANCER_TYPE_GROUP,
	FDS_PATHWAY,
	NO_PATIENTS,
	NO_COMPLIANT,
	NO_BREACHES,
	STANDARD_PERFORMANCE,
	TARGET,
	TWO_WEEK_WAIT_DAYS_WITHIN_14,
	TWO_WEEK_WAIT_DAYS_15_TO_16,
	TWO_WEEK_WAIT_DAYS_17_TO_21,
	TWO_WEEK_WAIT_DAYS_22_TO_28,
	TWO_WEEK_WAIT_DAYS_MORE_THAN_28,
	FDS_DAYS_WITHIN_14,
	FDS_DAYS_15_TO_28,
	FDS_DAYS_29_TO_42,
	FDS_DAYS_43_TO_62,
	FDS_DAYS_MORE_THAN_62,
	D31_DAYS_WITHIN_31,
	D31_DAYS_32_TO_38,
	D31_DAYS_39_TO_48,
	D31_DAYS_49_TO_62,
	D31_DAYS_MORE_THAN_62,
	D62_DAYS_WITHIN_31,
	D62_DAYS_32_TO_38,
	D62_DAYS_39_TO_48,
	D62_DAYS_49_TO_62,
	D62_DAYS_63_TO_76,
	D62_DAYS_77_TO_90,
	D62_DAYS_91_TO_104,
	D62_DAYS_MORE_THAN_104
) target_lag = '2 hours' refresh_mode = FULL initialize = ON_CREATE warehouse = NCL_ANALYTICS_XS
 COMMENT='Dynamic table which select most recent 4 financial years of data.'
 as
 
SELECT 

ROW_POPULATION_TYPE,
	DATE_PERIOD,
	FIN_YEAR,
	FIN_MONTH_NUMBER,
	FIN_MONTH_NAME,
	ORGANISATION_TYPE,
	ORGANISATION_CODE,
    -- Organisation_Key created to remove duplicates of ORGANISATION_CODE where one ORGANISATION_CODE maps to both ICB and Sub ICB. This Unique Key allows for Organisation Dimension table to be created in the PBI Dashbaord.
    ORGANISATION_CODE || '_' ||ORGANISATION_TYPE AS ORGANISATION_KEY,
	ORGANISATION_NAME,
    ORGANISATION_NAME_SHORT,
    ORGANISATION_REGION_CODE,
	ORGANISATION_REGION_NAME,
	ORGANISATION_ICB_CODE,
	ORGANISATION_ICB_NAME,
	CANCER_ALLIANCE,
	RADIOTHERAPY_NETWORK,
	STANDARD,
	CANCER_TYPE,
    CANCER_TYPE_SUBCATEGORY,
	CANCER_PATHWAY,
	CANCER_TYPE_GROUP,
	FDS_PATHWAY,
	NO_PATIENTS,
	NO_COMPLIANT,
	NO_BREACHES,
	STANDARD_PERFORMANCE,
	TARGET,
	TWO_WEEK_WAIT_DAYS_WITHIN_14,
	TWO_WEEK_WAIT_DAYS_15_TO_16,
	TWO_WEEK_WAIT_DAYS_17_TO_21,
	TWO_WEEK_WAIT_DAYS_22_TO_28,
	TWO_WEEK_WAIT_DAYS_MORE_THAN_28,
	FDS_DAYS_WITHIN_14,
	FDS_DAYS_15_TO_28,
	FDS_DAYS_29_TO_42,
	FDS_DAYS_43_TO_62,
	FDS_DAYS_MORE_THAN_62,
	D31_DAYS_WITHIN_31,
	D31_DAYS_32_TO_38,
	D31_DAYS_39_TO_48,
	D31_DAYS_49_TO_62,
	D31_DAYS_MORE_THAN_62,
	D62_DAYS_WITHIN_31,
	D62_DAYS_32_TO_38,
	D62_DAYS_39_TO_48,
	D62_DAYS_49_TO_62,
	D62_DAYS_63_TO_76,
	D62_DAYS_77_TO_90,
	D62_DAYS_91_TO_104,
	D62_DAYS_MORE_THAN_104

FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY

--SELECT Previous 4 Financial Years
WHERE FIN_YEAR >= (
    SELECT MIN(FIN_YEAR)
    FROM (
        SELECT DISTINCT FIN_YEAR
        FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY
        ORDER BY FIN_YEAR DESC
        LIMIT 4
    ) t)

-- 'All Cancers' and 'Combined' removed to get rid of duplicated data
AND CANCER_TYPE <> 'All Cancers'
AND CANCER_PATHWAY NOT IN ('Combined', 'Rare Cancer')
;