CREATE OR REPLACE VIEW DEV__MODELLING.CANCER__CWT_NATIONAL.RANKING__BY_CANCER_ALLIANCE
COMMENT = 'Dataset to rank Cancer Alliances against the FDS, 31 Day, and 62 Day cancer performance metrics.\nContact: jake.kealey@nhs.net'
AS;

--CTE to get main columns of interest and limit data to 
WITH BASE_PER AS (
    SELECT 
        DATE_PERIOD,
        FIN_YEAR,
        FIN_MONTH_NUMBER
        FIN_MONTH_NAME,
        CANCER_ALLIANCE,
        STANDARD,
        CANCER_TYPE,
        SUM(NO_PATIENTS) AS NO_PATIENTS,
        SUM(NO_COMPLIANT) AS NO_COMPLIANT,
        TO_NUMBER(NO_COMPLIANT / NO_PATIENTS, 10, 2) AS STANDARD_PERFORMANCE,
        TO_NUMBER(AVG(TARGET), 10, 2) AS TARGET
    FROM MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY
    WHERE ROW_POPULATION_TYPE = 'Provider'
    AND CANCER_TYPE_GROUP = 'Cancer Type'
    AND ORGANISATION_CODE != 'ALL ENGLISH PROVIDERS'
    
    GROUP BY ALL
),

--CTE to get ENGLAND level data including the total activity for each
--  DATE_PERIOD, STANDARD, CANCER_TYPE combination
OVERALL AS (
    SELECT 
        DATE_PERIOD,
        STANDARD,
        CANCER_TYPE,
        SUM(NO_PATIENTS) AS NO_PATIENTS_ENGLAND,
        SUM(NO_COMPLIANT) / SUM(NO_PATIENTS) AS STANDARD_PERFORMANCE_ENGLAND
    FROM BASE_PER
    GROUP BY ALL
)

SELECT 
    BASE_PER.*,
    (BASE_PER.NO_PATIENTS >= 10
    OR BASE_PER.NO_PATIENTS >= NO_PATIENTS_ENGLAND * 0.01) AS SIGNIFICANT_ACTIVITY,
    
    --Get Provider rank for each DATE_PERIOD, STANDARD, CANCER_TYPE combination
    CASE
        WHEN SIGNIFICANT_ACTIVITY
        THEN
            RANK() OVER (
                PARTITION BY SIGNIFICANT_ACTIVITY, BASE_PER.DATE_PERIOD, BASE_PER.CANCER_TYPE, BASE_PER.STANDARD 
                ORDER BY STANDARD_PERFORMANCE DESC
            )
        ELSE NULL
        END AS RANK_PERFORMANCE,
    --Get a count of the number of organisations included in each ranking
    CASE
        WHEN SIGNIFICANT_ACTIVITY
        THEN 
            COUNT(DISTINCT CANCER_ALLIANCE) OVER (
                PARTITION BY SIGNIFICANT_ACTIVITY, BASE_PER.DATE_PERIOD, BASE_PER.CANCER_TYPE, BASE_PER.STANDARD
            )
        ELSE NULL
    END AS RANK_DENOMINATOR,
    
    --Unadjusted version of the rank columns
    RANK() OVER (
        PARTITION BY BASE_PER.DATE_PERIOD, BASE_PER.CANCER_TYPE, BASE_PER.STANDARD 
        ORDER BY STANDARD_PERFORMANCE DESC
    ) AS UNADJUSTED_RANK_PERFORMANCE,
    --Get a count of the number of organisations included in each ranking
    COUNT(DISTINCT CANCER_ALLIANCE) OVER (
        PARTITION BY BASE_PER.DATE_PERIOD, BASE_PER.CANCER_TYPE, BASE_PER.STANDARD
    ) AS UNADJUSTED_RANK_DENOMINATOR,
    
    NO_PATIENTS_ENGLAND
    
FROM BASE_PER

LEFT JOIN OVERALL
ON BASE_PER.DATE_PERIOD = OVERALL.DATE_PERIOD
AND BASE_PER.STANDARD = OVERALL.STANDARD
AND BASE_PER.CANCER_TYPE = OVERALL.CANCER_TYPE

WHERE 1=1
AND BASE_PER.STANDARD IN ('FDS', '31 Day', '62 Day')

--Criteria for row to be included in rankings
-- AND (
--     BASE_PER.NO_PATIENTS >= 10
--     OR BASE_PER.NO_PATIENTS >= NO_PATIENTS_ENGLAND * 0.01
-- )

ORDER BY DATE_PERIOD DESC, CANCER_TYPE, STANDARD