CREATE OR REPLACE PROCEDURE DEV__MODELLING.CANCER__CWT_NATIONAL.CREATE_CWT_NATIONAL_MONTHLY()
RETURNS VARCHAR
LANGUAGE SQL
AS 
$$
BEGIN

--Description: Cleaned dataset for the CWT National level data
--Author: Jake Kealey

CREATE OR REPLACE TABLE DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY
AS
SELECT
    ROW_POPULATION_TYPE,
    
    --Date Fields
    "ReportDate" AS DATE_PERIOD,
    CASE 
        WHEN MONTH("ReportDate") < 4 
        THEN CONCAT(YEAR("ReportDate") - 1, '-', YEAR("ReportDate") - 2000)
        ELSE CONCAT(YEAR("ReportDate"), '-', YEAR("ReportDate") - 1999)
    END AS FIN_YEAR,

    CASE 
        WHEN MONTH("ReportDate") < 4 
        THEN MONTH("ReportDate") + 9
        ELSE MONTH("ReportDate") - 3
    END AS FIN_MONTH_NUMBER,
    MONTHNAME("ReportDate") AS FIN_MONTH_NAME,

    --Organisation Fields
    ORGANISATION_TYPE,
    ORGANISATION_CODE,
    org."Organisation_Name" AS ORGANISATION_NAME,
    CASE ORGANISATION_TYPE
        WHEN 'Provider' THEN par."Organisation_Name"
        WHEN 'CCG' THEN COALESCE(par."Organisation_Name", org_ccg.ICB_NAME)
        WHEN 'Sub-ICB' THEN par."Organisation_Name"
        WHEN 'ICB' THEN org."Organisation_Name"
    END AS ORGANISATION_ICB_NAME,

    --Breakdown Fields
    STANDARD,
    CASE 
        WHEN TYPE_OF_CANCER_CLEAN IN('Cancer - Non-Specific Symptoms', 'Exhibited (Non-Cancer) Breast Symptoms - Cancer Not Initially Suspected')
            THEN TYPE_OF_CANCER_CLEAN
        WHEN TYPE_OF_CANCER_CLEAN LIKE '% - %' 
            THEN LEFT(TYPE_OF_CANCER, CHARINDEX('-', TYPE_OF_CANCER, 0) - 2)
        ELSE TYPE_OF_CANCER_CLEAN
    END AS CANCER_TYPE,
    CASE 
        WHEN TYPE_OF_CANCER_CLEAN IN('Cancer - Non-Specific Symptoms', 'Exhibited (Non-Cancer) Breast Symptoms - Cancer Not Initially Suspected')
            THEN NULL
        WHEN TYPE_OF_CANCER_CLEAN LIKE '% - %' 
            THEN RIGHT(TYPE_OF_CANCER_CLEAN, LEN(TYPE_OF_CANCER_CLEAN) - CHARINDEX('-', TYPE_OF_CANCER_CLEAN, 0))
    END AS CANCER_TYPE_SUBCATEGORY,
    
    CASE 
        --2WW
        WHEN CANCER_TYPE = '2-WEEK WAIT - ALL SUSPECTED CANCER' THEN 'Combined'
        WHEN CANCER_TYPE = '2-WEEK WAIT - BREAST SYMPTOMS (CANCER NOT INITALLY SUSPECTED)' THEN 'Breast Symptomatic'
        WHEN CANCER_TYPE = '2-WEEK WAIT - SUSPECTED BY CANCER TYPE' THEN 'USC'
        --FDS
        WHEN CANCER_TYPE LIKE '28%' THEN 'FDS'
        --31 Day
        WHEN CANCER_TYPE LIKE '31-DAY - FIRST%' THEN 'First'
        WHEN CANCER_TYPE LIKE '31-DAY - 2nd%' THEN 'Subsequent'
        WHEN CANCER_TYPE LIKE '31-DAY COMBINED%' THEN 'Combined'
        WHEN CANCER_TYPE LIKE '31-DAY WAIT - RARE%' THEN 'Rare Cancer'
        --62 Day
        WHEN CANCER_TYPE LIKE '62-DAY - BREAST%' THEN 'Breast Symptomatic'
        WHEN CANCER_TYPE LIKE '62-DAY BREAST%' THEN 'Breast Symptomatic'
        WHEN CANCER_TYPE LIKE '62-DAY - CONSULTANT%' THEN 'Consultant Upgrade'
        WHEN CANCER_TYPE LIKE '62-DAY - SCREENING%' THEN 'Screening'
        WHEN CANCER_TYPE LIKE '62-DAY URGENT%' THEN 'USC'
        WHEN CANCER_TYPE LIKE '62-DAY COMBINED%' THEN 'Combined'
        ELSE NULL
    END AS CANCER_PATHWAY,

    CASE
        WHEN TYPE_OF_CANCER_CLEAN = 'All Cancers' THEN 'All Cancers'
        WHEN CANCER_TYPE LIKE '%BY CANCER TYPE' THEN 'Cancer Type'
        WHEN CANCER_TYPE = '28 DAY FAST DIAGNOSIS (BY ROUTE)' THEN 'Cancer Type'
        WHEN TYPE_OF_CANCER_CLEAN IN ('Drugs', 'Surgery', 'Radiotherapy') OR (CANCER_TYPE LIKE '%(OTHER)') THEN 'Treatment'
        WHEN CANCER_PATHWAY IN ('Breast Symptomatic', 'Rare Cancer') THEN CANCER_PATHWAY
        ELSE NULL
    END AS CANCER_TYPE_GROUP,

    --Standard Metrics (Base)
    TOTAL AS NO_PATIENTS,
    CASE STANDARD
        WHEN '2-WEEK WAIT' THEN WITHIN_14_DAYS
        WHEN '28 DAY' THEN WITHIN_28_DAYS
        WHEN '31-DAY WAIT' THEN WITHIN_31_DAYS
        WHEN '62 DAY' THEN WITHIN_62_DAYS
    END AS NO_COMPLIANT,
    CASE STANDARD
        WHEN '2-WEEK WAIT' THEN AFTER_14_DAYS
        WHEN '28 DAY' THEN AFTER_28_DAYS
        WHEN '31-DAY WAIT' THEN AFTER_31_DAYS
        WHEN '62 DAY' THEN AFTER_62_DAYS
    END AS BREACHES,
    DIV0NULL(
        CASE STANDARD
            WHEN '2-WEEK WAIT' THEN WITHIN_14_DAYS
            WHEN '28 DAY' THEN WITHIN_28_DAYS
            WHEN '31-DAY WAIT' THEN WITHIN_31_DAYS
            WHEN '62 DAY' THEN WITHIN_62_DAYS
        END,
        TOTAL) AS STANDARD_PERFORMANCE,
    TARGET,

    --Standard Metrics (Breakdown)--
    --2WW
    CASE STANDARD WHEN '2-WEEK WAIT' THEN WITHIN_14_DAYS        END AS TWO_WEEK_WAIT_DAYS_WITHIN_14,
    CASE STANDARD WHEN '2-WEEK WAIT' THEN IN_15_TO_16_DAYS      END AS TWO_WEEK_WAIT_DAYS_15_TO_16,
    CASE STANDARD WHEN '2-WEEK WAIT' THEN IN_17_TO_21_DAYS      END AS TWO_WEEK_WAIT_DAYS_17_TO_21,
    CASE STANDARD WHEN '2-WEEK WAIT' THEN IN_22_TO_28_DAYS      END AS TWO_WEEK_WAIT_DAYS_22_TO_28,
    CASE STANDARD WHEN '2-WEEK WAIT' THEN AFTER_28_DAYS         END AS TWO_WEEK_WAIT_DAYS_MORE_THAN_28,
    
    --FDS 28 Days
    CASE STANDARD WHEN '28 DAY'      THEN WITHIN_14_DAYS        END AS FDS_DAYS_WITHIN_14,
    CASE STANDARD WHEN '28 DAY'      THEN IN_15_TO_28_DAYS      END AS FDS_DAYS_15_TO_28,
    CASE STANDARD WHEN '28 DAY'      THEN IN_29_TO_42_DAYS      END AS FDS_DAYS_29_TO_42,
    CASE STANDARD WHEN '28 DAY'      THEN IN_43_TO_62_DAYS      END AS FDS_DAYS_43_TO_62,
    CASE STANDARD WHEN '28 DAY'      THEN AFTER_62_DAYS         END AS FDS_DAYS_MORE_THAN_62,
    
    --31 Days
    CASE STANDARD WHEN '31-DAY WAIT' THEN WITHIN_31_DAYS        END AS D31_DAYS_WITHIN_31,
    CASE STANDARD WHEN '31-DAY WAIT' THEN WITHIN_32_TO_38_DAYS  END AS D31_DAYS_32_TO_38,
    CASE STANDARD WHEN '31-DAY WAIT' THEN WITHIN_39_TO_48_DAYS  END AS D31_DAYS_39_TO_48,
    CASE STANDARD WHEN '31-DAY WAIT' THEN WITHIN_49_TO_62_DAYS  END AS D31_DAYS_49_TO_62,
    CASE STANDARD WHEN '31-DAY WAIT' THEN AFTER_62_DAYS         END AS D31_DAYS_MORE_THAN_62,

    --62 Days
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_31_DAYS        END AS D62_DAYS_WITHIN_31,
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_32_TO_38_DAYS  END AS D62_DAYS_32_TO_38,
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_39_TO_48_DAYS  END AS D62_DAYS_39_TO_48,
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_49_TO_62_DAYS  END AS D62_DAYS_49_TO_62,
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_63_TO_76_DAYS  END AS D62_DAYS_63_TO_76,
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_77_TO_90_DAYS  END AS D62_DAYS_77_TO_90,
    CASE STANDARD WHEN '62 DAY'      THEN WITHIN_91_TO_104_DAYS END AS D62_DAYS_91_TO_104,
    CASE STANDARD WHEN '62 DAY'      THEN AFTER_104_DAYS        END AS D62_DAYS_MORE_THAN_104
    
FROM (
    SELECT
        --GP Registered Columns
        'GP Registered' AS ROW_POPULATION_TYPE,
        CCG_CODE AS ORGANISATION_CODE,
        CANCER__CWT_NATIONAL.CLEAN_TYPE_OF_CANCER(TYPE_OF_CANCER) AS TYPE_OF_CANCER_CLEAN,
        
        * EXCLUDE(CCG_CODE, CLINICAL_COMMISSIONING_GROUP)
    FROM DATA_LAKE.PMCT."CwtMonthlySourceAppendReviseComm"
    
    UNION ALL
    
    SELECT
        'Provider' AS ROW_POPULATION_TYPE,
        PROVIDER_CODE AS ORGANISATION_CODE,
        CANCER__CWT_NATIONAL.CLEAN_TYPE_OF_CANCER(TYPE_OF_CANCER) AS TYPE_OF_CANCER_CLEAN,
        --Need to name columns as order differs from the Comm table
        "ReportDate",
        CARE_SETTING, STANDARD, TYPE_OF_CANCER, CANCER_TYPE, TOTAL, WITHIN_14_DAYS, AFTER_14_DAYS, PERCENTAGE_SEEN_WITHIN_14_DAYS, WITHIN_31_DAYS, AFTER_31_DAYS, 
        PERCENTAGE_TREATED_WITHIN_31_DAYS, AFTER_62_DAYS, WITHIN_62_DAYS, PERCENTAGE_TREATED_WITHIN_62_DAYS, TARGET, ORGANISATION_TYPE, "CreateTS", WITHIN_28_DAYS, AFTER_28_DAYS, 
        PERCENTAGE_TOLD_WITHIN_28_DAYS, IN_15_TO_16_DAYS, IN_17_TO_21_DAYS, IN_22_TO_28_DAYS, WITHIN_32_TO_38_DAYS, WITHIN_39_TO_48_DAYS, WITHIN_49_TO_62_DAYS, WITHIN_63_TO_76_DAYS, 
        WITHIN_77_TO_90_DAYS, WITHIN_91_TO_104_DAYS, AFTER_104_DAYS, IN_15_TO_28_DAYS, IN_29_TO_42_DAYS, IN_43_TO_62_DAYS
    FROM DATA_LAKE.PMCT."CwtMonthlySourceAppendReviseProv"
)

LEFT JOIN "Dictionary"."dbo"."Organisation" org
ON ORGANISATION_CODE = org."Organisation_Code"

LEFT JOIN "Dictionary"."dbo"."Organisation" par
ON org."SK_OrganisationID_ParentOrg" = par."SK_OrganisationID"

--Join for old CCG codes
LEFT JOIN (
    SELECT 
        orgd."OrganisationCode_Child" AS CCG_CODE,
        org."Organisation_Name" AS ICB_NAME
    FROM "Dictionary"."dbo"."OrganisationDescendent" orgd
    
    LEFT JOIN "Dictionary"."dbo"."Organisation" org
    ON orgd."OrganisationCode_Root" = org."Organisation_Code"
    
    WHERE "OrganisationPrimaryRole_Root" = 'RO261'
    AND "OrganisationPrimaryRole_Child" = 'RO98'
) org_ccg
ON ORGANISATION_CODE = org_ccg.CCG_CODE;

END;
$$;