-- This pulls the most recent 4 financial years of data from the CWT National Monthly Modelling table
-- Contact: eric.pinto@nhs.net

create or replace dynamic table DEV__REPORTING.CANCER__CWT_SUMMARY_REPORTS.CWT_NATIONAL_DASHBOARD(
	ROW_POPULATION_TYPE,
	DATE_PERIOD,
	FIN_YEAR,
	FIN_MONTH_NUMBER,
	FIN_MONTH_NAME,
	ORGANISATION_TYPE,
	ORGANISATION_CODE,
	ORGANISATION_KEY,
	ORGANISATION_NAME,
	ORGANISATION_NAME_SHORT,
	ORGANISATION_REGION_CODE,
	ORGANISATION_REGION_NAME,
	ORGANISATION_ICB_CODE,
	ORGANISATION_ICB_NAME,
	CANCER_ALLIANCE,
	RADIOTHERAPY_NETWORK,
	STANDARD,
	CANCER_TYPE,
	CANCER_TYPE_SUBCATEGORY,
	CANCER_PATHWAY,
	CANCER_TYPE_GROUP,
	FDS_PATHWAY,
	NO_PATIENTS,
	NO_COMPLIANT,
	NO_BREACHES,
	STANDARD_PERFORMANCE,
	TARGET
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = NCL_ANALYTICS_XS
 COMMENT='Dynamic table which select most recent 4 years of data.'
 as
 
SELECT 

ROW_POPULATION_TYPE,
	DATE_PERIOD,
	FIN_YEAR,
	FIN_MONTH_NUMBER,
	FIN_MONTH_NAME,
	ORGANISATION_TYPE,
	ORGANISATION_CODE,
    -- Organisation_Key created to remove duplicates of ORGANISATION_CODE where one ORGANISATION_CODE maps to both ICB and Sub ICB. This Unique Key allows for Organisation Dimension table to be created in the PBI Dashbaord.
    ORGANISATION_CODE || '_' ||ORGANISATION_TYPE AS ORGANISATION_KEY,
	ORGANISATION_NAME,
    ORGANISATION_NAME_SHORT,
    ORGANISATION_REGION_CODE,
	ORGANISATION_REGION_NAME,
	ORGANISATION_ICB_CODE,
	ORGANISATION_ICB_NAME,
    CANCER_ALLIANCE,
	RADIOTHERAPY_NETWORK,
	STANDARD,
	CANCER_TYPE,
    CANCER_TYPE_SUBCATEGORY,
	CANCER_PATHWAY,
	CANCER_TYPE_GROUP,
	FDS_PATHWAY,
	NO_PATIENTS,
	NO_COMPLIANT,
	NO_BREACHES,
	STANDARD_PERFORMANCE,
	TARGET

FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY

--SELECT Previous 4 Financial Years
WHERE FIN_YEAR >= (
    SELECT MIN(FIN_YEAR)
    FROM (
        SELECT DISTINCT FIN_YEAR
        FROM DEV__MODELLING.CANCER__CWT_NATIONAL.CWT_NATIONAL_MONTHLY
        ORDER BY FIN_YEAR DESC
        LIMIT 4
    ) t)

-- 'Combined' removed to get rid of duplicated data. 'All Cancers' only included for Sub-ICB as there is no Cancer Site data. 
AND ((ORGANISATION_TYPE = 'Sub-ICB' AND CANCER_TYPE_GROUP IN ('All Cancers','Treatment'))
   OR (ORGANISATION_TYPE <> 'Sub-ICB' AND CANCER_TYPE_GROUP <> 'All Cancers'))
AND CANCER_PATHWAY NOT IN ('Rare Cancer', 'Combined')
AND ORGANISATION_NAME_SHORT NOT LIKE ('%Commissioning%')
AND ORGANISATION_TYPE NOT IN ('CCG');