create or replace task DEV__MODELLING.CANCER__CWT_NATIONAL.TASK_CWT_NATIONAL_MONTHLY
	warehouse=NCL_ANALYTICS_XS
	schedule='USING CRON 0 12-16 * * THU-FRI Europe/London'
	as CALL DEV__MODELLING.CANCER__CWT_NATIONAL.CREATE_CWT_NATIONAL_MONTHLY();