--Use CTRL+F to replace "DEV__" with "" to update PROD. This is so DEV can be tested first before pushing to PROD

ALTER DYNAMIC TABLE DEV__MODELLING.CANCER__EMIS.FIT REFRESH;
ALTER DYNAMIC TABLE DEV__MODELLING.CANCER__EMIS.SAFETY_NETTING_AND_CCR REFRESH;
ALTER DYNAMIC TABLE DEV__MODELLING.CANCER__EMIS.SOCIAL_PRESCRIBING REFRESH;
ALTER DYNAMIC TABLE DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__EMIS__FIT REFRESH;
ALTER DYNAMIC TABLE DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__EMIS__SAFETY_NETTING_AND_CCR REFRESH;
ALTER DYNAMIC TABLE DEV__REPORTING.CANCER__PRIMARY_CARE_DASHBOARD.CANCER__EMIS__SOCIAL_PRESCRIBING REFRESH;